name: Deploy Worker
on:
  push:
    branches:
      - main

env:
  CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
  CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4

      - name: install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8
          run_install: false

      - name: install node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "pnpm"

      - name: install dependencies
        run: pnpm install

      - name: Apply migrations
        run: pnpm run db:migrate:remote

      - name: Deploy App
        run: pnpm run deploy
